# Generated by Django 4.2.11 on 2024-04-25 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_post_create_post_review_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Create',
            new_name='Create',
        ),
        migrations.RenameModel(
            old_name='Post_Review',
            new_name='Review',
        ),
    ]
