# Generated by Django 4.2.11 on 2024-04-29 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_rename_post_create_create_rename_post_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
),
        migrations.AlterField(
            model_name='create',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feed_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feed_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
